name: 'Code Formatting Checker'
description: 'Checks if code formatting guidelines are followed in pull requests.'
author: 'Your Name'
inputs:
  github-token:
    description: 'GitHub token to authenticate with the API.'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
